FROM node:latest

# RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173

RUN npm install -g serve

CMD [ "npm", "run", "dev" ]

# CMD ["serve", "-s", "build", "-l", "5173"]

# CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]


