version: "3"
services:
  python:
    image: python:latest
    build: 
      context: .
      dockerfile: Dockerfile.python
    links:
      - postgres
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
