version: "3"
services:
  python:
    image: python:latest
    build: 
      context: .
      dockerfile: Dockerfile.python
    links:
      - postgres
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.redis
    ports:
      - 6379:6379
    # volumes:
    #   - redis-data:/data
    command: redis-server --loglevel warning --requirepass password
volumes:
  postgres-data:
  # redis-data:
