FROM node:latest

WORKDIR /app

COPY ./forecast-vite/package.json .
COPY ./forecast-vite/package-lock.json .

RUN npm install

COPY ./forecast-vite .

RUN npm run build

EXPOSE 3000

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]

