version: "3.9"
services:
  python:
    image: python:latest
    build: .
    links:
      - postgres
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neural
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
