version: '3.1'
services:
  python:
    image: python:latest
    command: python -m http.server 8000
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: