version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    build: 
      context: .
      dockerfile: Dockerfile.redis
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    depends_on:
      - redis
  frontend:
    build: 
      context: ./forecast-vite
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
  # python:
  #   image: python:latest
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.python
  #   links:
  #     - postgres
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  # postgres:
  #   image: postgres:latest
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data:

