FROM python:latest

WORKDIR /app

COPY requirements_backend.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_backend.txt

COPY . .

EXPOSE 5000
ENV FLASK_APP=server_flask.py

CMD ["python", "server_flask.py"]

