version: "3"
services:
  python:
    image: python:latest
    build: 
      context: .
      dockerfile: Dockerfile.python
    links:
      - postgres
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  frontend:
    image: node:latest
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    depends_on:
      - redis

  backend:
    image: flask:latest
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
volumes:
  postgres-data:
